/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    getRandomLocations
 * Signature: (I)[LLocation;
 */
JNIEXPORT jobjectArray JNICALL Java_Hello_getRandomLocations
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
